name: aplikasi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/fitur1.png
    - assets/images/fitur2.png
    - assets/images/fitur3.png
    - assets/images/eye-on.png
    - assets/images/eye-off.png
    - assets/images/logo-google.png
    - assets/images/logo-fb.png
    - assets/images/admin.png
    - assets/images/reseller.png
    - assets/images/susu-jj.png
    - assets/images/profile.png
    - assets/images/jj3.png
    - assets/images/jj4.png
    - assets/images/pict-2.png
    - assets/images/pict-3.png
    - assets/images/pict-1.png
    - assets/images/pp.png
    - assets/images/world_map.png
    - assets/icons/cart.png
    - assets/icons/home.png
    - assets/icons/chat.png
    - assets/icons/user.png
    - assets/icons/back.png
    - assets/icons/setting.png
    - assets/icons/order.png
    - assets/icons/info.png
    - assets/icons/logout.png
    - assets/icons/next.png
    - assets/icons/send.png
    - assets/icons/notification.png
    - assets/sounds/backsound_arbiv.mp3
    - assets/sounds/sound.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
