name: aplikasi
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/image-for-logo/logo.png
    - images/image-for-fitur1/fitur1.png
    - images/image-for-fitur2/fitur2.png
    - images/image-for-fitur3/fitur3.png
    - images/image-for-login/eye-on.png
    - images/image-for-login/eye-off.png
    - images/image-for-login/logo-google.png
    - images/image-for-login/logo-fb.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
